version: '3.8'
services:
  db:
    image: postgres:13.2
    ports:
      - 5449:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: exchange
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/exchange:delegated
    links:
      - db
    environment:
      DATABASE_URL: "postgresql://root:root@db:5432/exchange"
      APP_URL: "http://exchange.local:8099"
      APP_ENV: "dev"
      APP_SECRET: "50bc5c94dc493ff013f532b21bb4d2b8"
      APP_HOSTNAME: "exchange.local"
      CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'

  nginx:
    image: nginx:1.19
    ports:
      - "8099:80"
    volumes:
      - .:/var/www/exchange:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
volumes:
  db-data: